name: Build

on:
    push:
        branches: '**'
        paths:
            - 'src/**'
            - 'generateFlavours/**'
            - 'gradle.properties'
            - '**.gradle.kts'
    pull_request:
        branches: '**'
        paths:
            - 'src/**'
            - 'generateFlavours/**'
            - 'gradle.properties'
            - '**.gradle.kts'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-node@v3
                with:
                    node-version: 16
                    cache: yarn

            -   name: Setup Java
                uses: actions/setup-java@v3
                with:
                    distribution: zulu
                    java-version: 11
                    cache: 'gradle'

            -   name: Install dependencies & build
                run: |
                    yarn install --frozen-lockfile
                    yarn build

            -   name: Lint
                run: yarn lint

            -   name: Generate All Flavours
                run: ./generateFlavours/main.ts

            -   name: Build Plugin
                run: ./gradlew buildPlugin

            -   name: Upload JAR
                uses: actions/upload-artifact@v3
                with:
                    name: "Tbh Theme-Snapshot.jar"
                    path: build/libs/*.jar

            -   name: Output Unreleased Changes
                run: |
                    echo "# 🚧 Unreleased 🚧" >> $GITHUB_STEP_SUMMARY
                    echo "$(./gradlew getChangelog --unreleased --no-header --console=plain -q)" >> $GITHUB_STEP_SUMMARY
